// This file is normally generated by `supabase gen types typescript --local`.
// It's checked in here as a hand-authored fallback so the project type-checks
// before you run the codegen. Once you run `npm run supabase:types` it will
// be overwritten with the canonical generated types.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type BookingStatus =
  | "pending"
  | "confirmed"
  | "cancelled"
  | "completed";

export type UserRole = "admin" | "customer";
export type EmployeeRole =
  | "employee"
  | "tourguide"
  | "scubaguide"
  | "instructor";

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          role: UserRole;
          full_name: string | null;
          phone: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          role?: UserRole;
          full_name?: string | null;
          phone?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]>;
        Relationships: [];
      };
      categories: {
        Row: {
          id: string;
          slug: string;
          name: string;
          tagline: string | null;
          description: string | null;
          icon: string | null;
          hero_image: string | null;
          sort_order: number;
          created_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          tagline?: string | null;
          description?: string | null;
          icon?: string | null;
          hero_image?: string | null;
          sort_order?: number;
          created_at?: string;
          deleted_at?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["categories"]["Insert"]>;
        Relationships: [];
      };
      locations: {
        Row: {
          id: string;
          slug: string;
          name: string;
          region: string | null;
          description: string | null;
          hero_image: string | null;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          region?: string | null;
          description?: string | null;
          hero_image?: string | null;
          sort_order?: number;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["locations"]["Insert"]>;
        Relationships: [];
      };
      activities: {
        Row: {
          id: string;
          slug: string;
          category_id: string;
          subcategory_id: string | null;
          name: string;
          short_description: string | null;
          description: string | null;
          duration_minutes: number | null;
          price_cents: number | null;
          currency: string;
          min_party: number;
          max_party: number;
          image_url: string | null;
          gallery_urls: string[] | null;
          availability_label: string | null;
          is_published: boolean;
          is_featured: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          category_id: string;
          subcategory_id?: string | null;
          name: string;
          short_description?: string | null;
          description?: string | null;
          duration_minutes?: number | null;
          price_cents?: number | null;
          currency?: string;
          min_party?: number;
          max_party?: number;
          image_url?: string | null;
          gallery_urls?: string[] | null;
          availability_label?: string | null;
          is_published?: boolean;
          is_featured?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["activities"]["Insert"]>;
        Relationships: [
          {
            foreignKeyName: "activities_category_id_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "activities_subcategory_id_fkey";
            columns: ["subcategory_id"];
            isOneToOne: false;
            referencedRelation: "subcategories";
            referencedColumns: ["id"];
          },
        ];
      };
      subcategories: {
        Row: {
          id: string;
          category_id: string;
          slug: string;
          name: string;
          description: string | null;
          sort_order: number;
          deleted_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          category_id: string;
          slug: string;
          name: string;
          description?: string | null;
          sort_order?: number;
          deleted_at?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["subcategories"]["Insert"]>;
        Relationships: [
          {
            foreignKeyName: "subcategories_category_id_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id"];
          },
        ];
      };
      activity_locations: {
        Row: {
          activity_id: string;
          location_id: string;
        };
        Insert: {
          activity_id: string;
          location_id: string;
        };
        Update: Partial<
          Database["public"]["Tables"]["activity_locations"]["Insert"]
        >;
        Relationships: [
          {
            foreignKeyName: "activity_locations_activity_id_fkey";
            columns: ["activity_id"];
            isOneToOne: false;
            referencedRelation: "activities";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "activity_locations_location_id_fkey";
            columns: ["location_id"];
            isOneToOne: false;
            referencedRelation: "locations";
            referencedColumns: ["id"];
          },
        ];
      };
      activity_cost_templates: {
        Row: {
          id: string;
          activity_id: string;
          default_fuel_cost_cents: number;
          default_fuel_hourly_cost_cents: number;
          default_tank_cost_cents: number;
          default_tank_qty: number;
          default_tank_unit_cost_cents: number;
          default_gear_cost_cents: number;
          default_gear_qty: number;
          default_gear_unit_cost_cents: number;
          default_other_cost_cents: number;
          default_instructor_hours: number;
          updated_at: string;
        };
        Insert: {
          id?: string;
          activity_id: string;
          default_fuel_cost_cents?: number;
          default_fuel_hourly_cost_cents?: number;
          default_tank_cost_cents?: number;
          default_tank_qty?: number;
          default_tank_unit_cost_cents?: number;
          default_gear_cost_cents?: number;
          default_gear_qty?: number;
          default_gear_unit_cost_cents?: number;
          default_other_cost_cents?: number;
          default_instructor_hours?: number;
          updated_at?: string;
        };
        Update: Partial<
          Database["public"]["Tables"]["activity_cost_templates"]["Insert"]
        >;
        Relationships: [
          {
            foreignKeyName: "activity_cost_templates_activity_id_fkey";
            columns: ["activity_id"];
            isOneToOne: false;
            referencedRelation: "activities";
            referencedColumns: ["id"];
          },
        ];
      };
      bookings: {
        Row: {
          id: string;
          reference: string;
          activity_id: string;
          location_id: string | null;
          employee_id: string | null;
          customer_name: string;
          customer_email: string;
          customer_phone: string;
          party_size: number;
          preferred_date: string;
          preferred_time: string | null;
          special_requests: string | null;
          status: BookingStatus;
          internal_notes: string | null;
          quoted_total_cents: number;
          quoted_currency: string;
          payment_status: "unpaid" | "partial" | "paid" | "refunded";
          amount_paid_cents: number;
          payment_method_mock: string | null;
          paid_at: string | null;
          fuel_cost_cents: number;
          tank_cost_cents: number;
          tank_qty: number;
          tank_unit_cost_cents: number;
          gear_cost_cents: number;
          gear_qty: number;
          gear_unit_cost_cents: number;
          other_cost_cents: number;
          instructor_hours: number;
          instructor_payout_cents: number;
          total_cost_cents: number;
          estimated_profit_cents: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          reference?: string;
          activity_id: string;
          location_id?: string | null;
          employee_id?: string | null;
          customer_name: string;
          customer_email: string;
          customer_phone: string;
          party_size: number;
          preferred_date: string;
          preferred_time?: string | null;
          special_requests?: string | null;
          status?: BookingStatus;
          internal_notes?: string | null;
          quoted_total_cents?: number;
          quoted_currency?: string;
          payment_status?: "unpaid" | "partial" | "paid" | "refunded";
          amount_paid_cents?: number;
          payment_method_mock?: string | null;
          paid_at?: string | null;
          fuel_cost_cents?: number;
          tank_cost_cents?: number;
          tank_qty?: number;
          tank_unit_cost_cents?: number;
          gear_cost_cents?: number;
          gear_qty?: number;
          gear_unit_cost_cents?: number;
          other_cost_cents?: number;
          instructor_hours?: number;
          instructor_payout_cents?: number;
          total_cost_cents?: number;
          estimated_profit_cents?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["bookings"]["Insert"]>;
        Relationships: [
          {
            foreignKeyName: "bookings_activity_id_fkey";
            columns: ["activity_id"];
            isOneToOne: false;
            referencedRelation: "activities";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "bookings_location_id_fkey";
            columns: ["location_id"];
            isOneToOne: false;
            referencedRelation: "locations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "bookings_employee_id_fkey";
            columns: ["employee_id"];
            isOneToOne: false;
            referencedRelation: "employees";
            referencedColumns: ["id"];
          },
        ];
      };
      employees: {
        Row: {
          id: string;
          employee_code: string;
          name: string;
          first_name: string | null;
          last_name: string | null;
          role: EmployeeRole;
          photo_url: string | null;
          credentials_url: string | null;
          expertise_level: string | null;
          certifications: string | null;
          is_active: boolean;
          payout_mode: "percent" | "hourly";
          payout_percent: number;
          hourly_rate_cents: number | null;
          overtime_hourly_rate_cents: number | null;
          phone: string | null;
          email: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          employee_code: string;
          name: string;
          first_name?: string | null;
          last_name?: string | null;
          role?: EmployeeRole;
          photo_url?: string | null;
          credentials_url?: string | null;
          expertise_level?: string | null;
          certifications?: string | null;
          is_active?: boolean;
          payout_mode?: "percent" | "hourly";
          payout_percent?: number;
          hourly_rate_cents?: number | null;
          overtime_hourly_rate_cents?: number | null;
          phone?: string | null;
          email?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["employees"]["Insert"]>;
        Relationships: [];
      };
      custom_booking_requests: {
        Row: {
          id: string;
          reference: string;
          customer_name: string;
          customer_email: string;
          customer_phone: string;
          preferred_date: string | null;
          preferred_time: string | null;
          party_size: number;
          location_id: string | null;
          budget_notes: string | null;
          quote_amount_cents: number | null;
          quote_currency: string;
          quote_expires_on: string | null;
          request_details: string;
          flexibility: "fixed" | "flexible";
          status: "new" | "quoted" | "approved" | "rejected" | "converted";
          admin_notes: string | null;
          employee_id: string | null;
          booking_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          reference?: string;
          customer_name: string;
          customer_email: string;
          customer_phone: string;
          preferred_date?: string | null;
          preferred_time?: string | null;
          party_size?: number;
          location_id?: string | null;
          budget_notes?: string | null;
          quote_amount_cents?: number | null;
          quote_currency?: string;
          quote_expires_on?: string | null;
          request_details: string;
          flexibility?: "fixed" | "flexible";
          status?: "new" | "quoted" | "approved" | "rejected" | "converted";
          admin_notes?: string | null;
          employee_id?: string | null;
          booking_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<
          Database["public"]["Tables"]["custom_booking_requests"]["Insert"]
        >;
        Relationships: [
          {
            foreignKeyName: "custom_booking_requests_booking_id_fkey";
            columns: ["booking_id"];
            isOneToOne: false;
            referencedRelation: "bookings";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "custom_booking_requests_employee_id_fkey";
            columns: ["employee_id"];
            isOneToOne: false;
            referencedRelation: "employees";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "custom_booking_requests_location_id_fkey";
            columns: ["location_id"];
            isOneToOne: false;
            referencedRelation: "locations";
            referencedColumns: ["id"];
          },
        ];
      };
      site_settings: {
        Row: {
          id: string;
          business_name: string;
          contact_email: string;
          whatsapp_number: string;
          timezone: string;
          hero_eyebrow: string | null;
          hero_title: string | null;
          hero_subtitle: string | null;
          hero_video_url: string | null;
          hero_poster_url: string | null;
          hero_primary_cta_label: string | null;
          hero_primary_cta_href: string | null;
          hero_secondary_cta_label: string | null;
          hero_secondary_cta_href: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_name?: string;
          contact_email?: string;
          whatsapp_number?: string;
          timezone?: string;
          hero_eyebrow?: string | null;
          hero_title?: string | null;
          hero_subtitle?: string | null;
          hero_video_url?: string | null;
          hero_poster_url?: string | null;
          hero_primary_cta_label?: string | null;
          hero_primary_cta_href?: string | null;
          hero_secondary_cta_label?: string | null;
          hero_secondary_cta_href?: string | null;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["site_settings"]["Insert"]>;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      create_booking_request: {
        Args: {
          p_activity_id: string;
          p_employee_id: string | null;
          p_location_id: string | null;
          p_customer_name: string;
          p_customer_email: string;
          p_customer_phone: string;
          p_party_size: number;
          p_preferred_date: string;
          p_preferred_time: string | null;
          p_special_requests: string | null;
        };
        Returns: string;
      };
      get_booking_confirmation_by_reference: {
        Args: { p_reference: string };
        Returns: {
          reference: string;
          customer_name: string;
          customer_email: string;
          customer_phone: string;
          party_size: number;
          preferred_date: string;
          preferred_time: string | null;
          special_requests: string | null;
          activity_name: string | null;
          location_name: string | null;
          status: BookingStatus;
          payment_status: string;
          quoted_total_cents: number;
        }[];
      };
      promote_to_admin: {
        Args: { target_email: string };
        Returns: undefined;
      };
    };
    Enums: {
      booking_status: BookingStatus;
      employee_role: EmployeeRole;
      user_role: UserRole;
    };
    CompositeTypes: Record<string, never>;
  };
}

export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];

export type Activity = Tables<"activities">;
export type Category = Tables<"categories">;
export type Subcategory = Tables<"subcategories">;
export type Location = Tables<"locations">;
export type Booking = Tables<"bookings">;
export type Profile = Tables<"profiles">;
export type Employee = Tables<"employees">;
